services:
  db:
    image: postgres:16
    environment: 
      POSTGRES_DB: emaildb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "123"
    ports:
      - "5434:5432"
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
      - ./dbInit/dbInit.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      REDIS_PASSWORD: ""
      REDIS_USER: "user"
      REDIS_USER_PASSWORD: ""
    ports:
      - "6380:6379"
    volumes:
      - ./redisdata:/data
  emailsender:
    build:
      dockerfile: services/register/Dockerfile
      context: .
    ports:
      - "8083:8083"
    depends_on:
      - redis
      - db